apiVersion: v1
kind: Pod
metadata:
  name: pv-debug-server
spec:
  containers:
    - image: lynn0706/netutils
      imagePullPolicy: Always
      name: debug-server
      volumeMounts:
        - mountPath: /test
          name: data-pvc
  volumes:
    - name: data-pvc
      persistentVolumeClaim:
        claimName: pvc-nfs
