apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lynn0706-role
rules:
  - apiGroups: ['']
    resources: ['pods', 'nodes', 'services']
    verbs: ['delete', 'get', 'list', 'patch', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lynn0706-role-binding
roleRef:
  kind: ClusterRole
  name: lynn0706-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: lynn0706
    namespace: default
