apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-pv-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath-pv-pvc
  template:
    metadata:
      labels:
        app: hostpath-pv-pvc
    spec:
      containers:
        - image: lynn0706/netutils
          name: c1
          volumeMounts:
            - mountPath: '/c1'
              name: hostpath-demo
      volumes:
        - name: hostpath-demo
          persistentVolumeClaim:
            claimName: hostpath-demo
