apiVersion: v1
kind: Pod
metadata:
  name: clusterfirstwithhost-true
  labels:
    app: myapp
spec:
  containers:
    - name: clusterfirstwithhost
      image: lynn0706/netutils
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
