apiVersion: v1
kind: Pod
metadata:
  name: clusterfirstwithhost
  labels:
    app: myapp
spec:
  containers:
    - name: clusterfirstwithhost
      image: lynn0706/netutils
  dnsPolicy: ClusterFirstWithHostNet
