apiVersion: v1
kind: Pod
metadata:
  name: clusterfirst-true
  labels:
    app: myapp
spec:
  containers:
    - name: clusterfirst
      image: lynn0706/netutils
  hostNetwork: true
  dnsPolicy: ClusterFirst
