apiVersion: v1
kind: Pod
metadata:
  name: none
  labels:
    app: myapp
spec:
  containers:
    - name: none
      image: lynn0706/netutils
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 8.8.8.8
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: '2'
      - name: edns0
